### ISSUE TITLE
! LaTeX Error: File `sectsty.sty' not found.

### ISSUE THREAD

**Issue by loulou4418** [teobiton/EnvSetUp#10]
Hello,

I installed the recommended package :
```
sudo apt-get install git inkscape texlive texlive-bibtex-extra make
```
But got an error during compilation during :
```
latex -output-format='pdf' -output-directory=./temp main.tex
```
BR

**Comment by loulou4418** [comment]
Hello @loulou4418,

here is the answer for you [https://tex.stackexchange.com/a/158721](https://tex.stackexchange.com/a/158721).

Installing ```texlive-full``` worked for me but it's **very** heavy

BR

**Comment by teobiton** [comment]
`texlive-full` is indeed a very large package but for optimal usage of Latex it is better to have it. Let's add it to the required packages.
